training:
    # training setting
    dataset: 'cifar10'
    model_type: 'resnet18'
    total_epochs: 100
    batch_size: 128
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    scheduler:
        - 75
        - 90
    num_classes: 10
    lower: 0
    upper: 1
    
    alpha: 2
    epsilon: 8
    num_repeats: 10
    tau: None
    lam: None
    lambda_av:
        - None
        - None
    gamma: None
    beta: None
    pm_type: None
    warm_up: None
    xi: None
    wc: 0.01
    wp: 0.0001
    lr_pc: 0.0001
    lr_center: 0.5
    
    
