training:
    # training setting
    dataset: 'cifar10'
    model_type: 'resnet18'
    total_epochs: 100
    batch_size: 128
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0004
    scheduler:
        - 75
        - 90
    num_classes: 10
    lower: 0
    upper: 1
    
    alpha: 2
    epsilon: 8
    num_repeats: 10
    tau: None
    lam: None
    lambda_av:
        - None
        - None
    gamma: None
    beta: 6.0
    pm_type: None
    warm_up: None
    xi: None
    wc: None
    wp: None
    lr_pc: None
    lr_center: None
    
    
